-- 這一筆在 Google 行事曆上的事件 id；NULL = 還沒匯入過。
--
-- 嚴格說它是冗餘的：event id 是從 note_items.id 決定性推算出來的
-- （見 CalendarEventIds），任何時候都算得回來。存下來是為了兩件事：
--
--   1. 當「匯入過沒有」的旗標——Flex 卡片上按鈕要顯示「加入行事曆」
--      還是「已加入・重新同步」，靠的是這一欄。
--   2. 萬一哪天推算規則改了（換前綴、換行事曆），舊資料還指得回原來那筆事件。
--
-- 不建唯一索引：同一個 id 在同一個行事曆裡的唯一性由 Google 那邊保證
-- （重複的 insert 回 409），這裡再設一次只是把外部系統的約束抄一份進來，
-- 而抄本一定會過期。
ALTER TABLE note_items ADD COLUMN google_event_id VARCHAR(128);
