# fly.toml app configuration file generated for smartvoiceassistant-black-wildflower-23 on 2024-05-07T17:49:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
  
app = 'smartvoiceassistant'
primary_region = 'nrt'

[build]
  image = "python:3.9"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
